# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XPvVl9r+7GuFOzp7Xf6zJvhGm0JCaKoezq2rpdDnnTd/2qSC6bcCY7B1ZaKCtEDMhGVnn+EZQzVamIUW4Xl/HHZULA/Ro4svkXYxxwJ5cuLBCmtQCQB2ewxPoIIewq8pNH2HFyg2lu9/wbmsELkFxsnLX6cVAmG9pOk41Jy7WONtx5vbiF13OkOoAQB4j2qIwFedcgu8dkqxKPRR+of1Y9yc/RE/aungHvESqqYNstlV99tTbJ3vfL138fjpCqef3B8VtepS8pF1uwfO7GDPI7M+bKV/on/KDRqbA9e7D1ZJvyTxTed3sNk5QVmElOKJeVoFT6qK8INPV7Y8+vFuyikXSpDZ0clVwuIV19/0vfrUxMczll0k4hRTgiYyqMQ2KLnJVd6k244DeAVPNTS6f8tX4MAf+zKw9jPukclZjZ9F3KmcQYd5p0wdeLusrlve6aARhSgZXT649pamsScdsaG8cAT3d+Tw+RdY44hXwTf3/giaZInJwelY3ff+wgoaiIYrYKHtr0jdIa/wPL7d/DvT8RzyRme6kcAK/YDXGAMpCriK+s22QA2CDThmHRx1fgUBRdeGcZhkCCs0r4kfyUL//B9xQdmXi5ezSF3hfK7GugLXzvUwOQe5btaydrGcIrbI0FP15shCdeUOpkLn0ZFVXrC9QQWF+lJl9m6X29Q="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
