travis:
  secure:
    BINSTAR_TOKEN: ZjBE9HWZL+e64QZJkrvXjFFzsqjVNLrJvA4ssnIjGTHZLjg9/omrmLBWw+nE9uCh9T5Ha3XTYcU2644998XqXW0AwDJKKzabvYrzzro0dzGYazJXdwVX22FMteOMTQ1LrEx91JX1wKYgsfFKrn+juGJxAscycI68/9lGcWyZ6D4gMmXTqj50LFK69AYobj/cpWcgOo+V5OpMcY1k0cLSiWNdhoqxmoozTRouolTwi0TT1OpSswz+JOenEfyOOiJXQI+UdRs4ct3a4CEzAOWgudie6zAmMMRaiZWZfWPIk8algf5xojUWQgAOJitCWsHYQBIyblTYX5YJ+BXdGXiwyQ1dv2hAeuJXCLNofWgSNyHJBxOEY9Q5UU1i1nCZJsqsu8jRIpSF8e2pqSPVrSOEDJqRkNO+QW7PPM4bweU53uaYnrTgS5LFy4lnHInxDnCSfs8O17Pvz8LrZlm1qwgxnROLiAYVlfr670Phh0heHlW6BLWgstOv9KakEZt+8X3WKxyj3BYsTODWhYuyklDMu73W9H/cAuZjs2UTFDbFQKgC6i69qFC035SMMf1JtBA3VDIAbYHa29a3ab/ce4oo6TmXz9Gf3NkiUl+nr4B+btKJGYE85I6eWSVnSHn7tubDNQBqCrmiM9449D30KX4uaAyyFQEg7mZVDQGZvl/Ct1M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
