appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: XPvVl9r+7GuFOzp7Xf6zJvhGm0JCaKoezq2rpdDnnTd/2qSC6bcCY7B1ZaKCtEDMhGVnn+EZQzVamIUW4Xl/HHZULA/Ro4svkXYxxwJ5cuLBCmtQCQB2ewxPoIIewq8pNH2HFyg2lu9/wbmsELkFxsnLX6cVAmG9pOk41Jy7WONtx5vbiF13OkOoAQB4j2qIwFedcgu8dkqxKPRR+of1Y9yc/RE/aungHvESqqYNstlV99tTbJ3vfL138fjpCqef3B8VtepS8pF1uwfO7GDPI7M+bKV/on/KDRqbA9e7D1ZJvyTxTed3sNk5QVmElOKJeVoFT6qK8INPV7Y8+vFuyikXSpDZ0clVwuIV19/0vfrUxMczll0k4hRTgiYyqMQ2KLnJVd6k244DeAVPNTS6f8tX4MAf+zKw9jPukclZjZ9F3KmcQYd5p0wdeLusrlve6aARhSgZXT649pamsScdsaG8cAT3d+Tw+RdY44hXwTf3/giaZInJwelY3ff+wgoaiIYrYKHtr0jdIa/wPL7d/DvT8RzyRme6kcAK/YDXGAMpCriK+s22QA2CDThmHRx1fgUBRdeGcZhkCCs0r4kfyUL//B9xQdmXi5ezSF3hfK7GugLXzvUwOQe5btaydrGcIrbI0FP15shCdeUOpkLn0ZFVXrC9QQWF+lJl9m6X29Q=
conda_forge_output_validation: true
