travis:
  secure:
    BINSTAR_TOKEN: tjrveFREKBpzYaa7gKVfeU633zucWiLLhmSfrXFrJ92CQ7+9BOuA3Jz4Go8Pxba1ADCVLRAl1eoCow/lOfxabt/hk5et1row0C+6PErH4ABZZmW5uNDlTdRcqp4sKX/1WBJScIvJNDjyI23WCGv//kRJSmXPTBbRIMkQPl0RrCxc3jrnqqPjzNddX7GL/0+DHMvlOPjsqRpihTG+x0PXsGEnMDdiWDqvtyoiCVCC9Td//twGQKnq6VRMPZ7yxwmGozjsAk/qOijpDZkvaeT0NDQQqK2p57C+VD51e1w9lMqUA65sqOy6/ar15KB1EjOJXCID9kaa52Da7G6SYPlA+YdMPNcxI5EkPl9kCJkPNQgz0RGi9mGm2LGgV+2gI1HAlgTmPknV6BCYdhjztWaCprkNY5l5z0SANy+A8+NdYUM+tFu9oAbwPWJW80Yg3BWulyk8TIABBQUT+R2lL/NWWMh21e1ecOgcq8ZzTilAJ8RnUbAaRkvYE3yibBLKsIWL5cuxhTf61vsXZMRo/N7akaWz2grPBzbggjOiPtlQuPgPsdLrRX3lXPfEx6X9wNgPfJD8bUxdKpUVR4cZtxj5aWtq7Zsv+SLMTy0nc5KVeXMszW6jLXfPiLq870hJ46EgjBYtlc6Q6h8hA4hSNgA0zLPNl0uQKQS/clNVqakH3jo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
